<?php

namespace mz\InventarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository {
    
    public function getSearchQuery($qParameter = ''){
        $qb=$this->createQueryBuilder('e');
        $qb->select('e')
                ->where('e.nombre LIKE :q')
                ->orWhere('e.marca LIKE :q')
                ->orWhere('e.modelo LIKE :q')
                ->orWhere('e.sn LIKE :q')
                ->orWhere('e.codigo LIKE :q')
                ->setParameter('q', '%'.$qParameter.'%');
            ;
        return $qb;
    }
    
}
