<?php

namespace mz\InventarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
    public function getSearchQuery($qParameter = ''){
        $qb=$this->createQueryBuilder('e');
        $qb->select('e')
                ->where('e.apellido LIKE :q')
                ->orWhere('e.nombre LIKE :q')
                ->orWhere('e.email LIKE :q')
                ->orWhere('e.username LIKE :q')
                ->setParameter('q', '%'.$qParameter.'%');
            ;
        return $qb;
    }
}
