parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: inventario_dev
    database_user: root
    database_password: toor
    database_path: null

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    locale: en
    secret: 98449116bcfe11063e49e39e9091b3ae4
