security:
    encoders:
        mz\InventarioBundle\Entity\Usuario:
            algorithm: sha512
            encode-as-base64: true
            iterations: 13

    providers:
        user_db:
            entity: { class: mz\InventarioBundle\Entity\Usuario, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
#            http_basic:
#                realm: "Introduzca Usuario y Contraseña"
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/usuarios, roles: ROLE_ADMIN }
        - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] }