condicion:
    pattern:  /
    defaults: { _controller: "G4InventarioBundle:Condicion:index" }

condicion_show:
    pattern:  /{id}/show
    defaults: { _controller: "G4InventarioBundle:Condicion:show" }

condicion_new:
    pattern:  /new
    defaults: { _controller: "G4InventarioBundle:Condicion:new" }

condicion_create:
    pattern:  /create
    defaults: { _controller: "G4InventarioBundle:Condicion:create" }
    requirements: { _method: post }

condicion_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "G4InventarioBundle:Condicion:edit" }

condicion_update:
    pattern:  /{id}/update
    defaults: { _controller: "G4InventarioBundle:Condicion:update" }
    requirements: { _method: post }

condicion_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "G4InventarioBundle:Condicion:delete" }
    requirements: { _method: post }
