G4\InventarioBundle\Entity\Categoria:
    type: entity
    table: categorias
    repositoryClass: G4\InventarioBundle\Entity\CategoriaRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        nombre:
            type: string
            length: 255
            unique: true
        slug:
            type: string
            length: 255
            unique: true
    oneToMany:
        items:
            targetEntity: Item
            mappedBy: categoria
    lifecycleCallbacks:
        prePersist: [ setSlugValue ]
        preUpdate: [ setSlugValue ]
