G4\InventarioBundle\Entity\Imagen:
    type: entity
    table: imagenes
    repositoryClass: G4\InventarioBundle\Entity\ImagenRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        ruta:
            type: string
            length: 255
    manyToOne:
        item:
            targetEntity: Item
            inversedBy: imagenes
            joinColumn:
                name: item_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
