G4\InventarioBundle\Entity\Item:
    type: entity
    table: items
    repositoryClass: G4\InventarioBundle\Entity\ItemRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        nombre:
            type: string
            length: 255
        marca:
            type: string
            length: 255
        modelo:
            type: string
            length: 255
        sn:
            type: string
            length: 255
        fechaCompra:
            type: date
            column: fecha_compra
            nullable: true
        costo:
            type: decimal
            scale: 2
            nullable: true
        garantia:
            type: integer
        descripcion:
            type: text
        codigoInventario:
            type: string
            length: 255
            column: codigo_inventario
            nullable: true
            unique: true
        codigoItem:
            type: string
            length: 255
            column: codigo_item
            unique: true
        createdAt:
            type: datetime
            column: created_at
        createdBy:
            type: string
            length: 255
            column: created_by
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
        updatedBy:
            type: string
            length: 255
            column: updated_by
            nullable: true
    manyToOne:
        categoria:
            targetEntity: Categoria
            inversedBy: items
            joinColumn:
                name: categoria_id
                referencedColumnName: id
        condicion:
            targetEntity: Condicion
            inversedBy: items
            joinColumn:
                name: condicion_id
                referencedColumnName: id
        estado:
            targetEntity: Estado
            inversedBy: items
            joinColumn:
                name: estado_id
                referencedColumnName: id
        ubicacion:
            targetEntity: Ubicacion
            inversedBy: items
            joinColumn:
                name: ubicacion_id
                referencedColumnName: id
    oneToMany:
        imagenes:
            targetEntity: Imagen
            mappedBy: item
        prestamos:
            targetEntity: Prestamo
            mappedBy: item
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue, setCreatedByValue, setCodigoItemValue ]
        preUpdate: [ setUpdatedAtValue, setUpdatedByValue ]
