G4\InventarioBundle\Entity\Prestamo:
    type: entity
    table: prestamos
    repositoryClass: G4\InventarioBundle\Entity\PrestamoRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        apellido:
            type: string
            length: 255
        nombre:
            type: string
            length: 255
        dni:
            type: string
            length: 255
        fecha:
            type: date
        fechaDevolucion:
            type: date
            column: fecha_devolucion
            nullable: true
        observaciones:
            type: text
        createdAt:
            type: datetime
            column: created_at
        createdBy:
            type: string
            length: 255
            column: created_by
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
        updatedBy:
            type: string
            length: 255
            column: updated_by
            nullable: true
    manyToOne:
        item:
            targetEntity: Item
            inversedBy: prestamos
            joinColumn:
                name: item_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue, setCreatedByValue ]
        preUpdate: [ setUpdatedAtValue, setUpdatedByValue ]
