G4\InventarioBundle\Entity\Ubicacion:
    type: entity
    table: ubicaciones
    repositoryClass: G4\InventarioBundle\Entity\UbicacionRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: 255
            unique: true
        slug:
            type: string
            length: 255
            unique: true
    oneToMany:
        items:
            targetEntity: Item
            mappedBy: ubicacion
    lifecycleCallbacks:
        prePersist: [ setSlugValue ]
        preUpdate: [ setSlugValue ]
