G4\InventarioBundle\Entity\Usuario:
    type: entity
    table: usuarios
    repositoryClass: G4\InventarioBundle\Entity\UsuarioRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        apellido:
            type: string
            length: 255
        nombre:
            type: string
            length: 255
        email:
            type: string
            length: 255
            unique: true
        username:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
        isEnabled:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
