usuario:
    pattern:  /
    defaults: { _controller: "mzInventarioBundle:AdminUsuarios:index" }

usuario_show:
    pattern:  /{id}/show
    defaults: { _controller: "mzInventarioBundle:AdminUsuarios:show" }

usuario_new:
    pattern:  /new
    defaults: { _controller: "mzInventarioBundle:AdminUsuarios:new" }

usuario_create:
    pattern:  /create
    defaults: { _controller: "mzInventarioBundle:AdminUsuarios:create" }
    requirements: { _method: post }

usuario_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "mzInventarioBundle:AdminUsuarios:edit" }

usuario_update:
    pattern:  /{id}/update
    defaults: { _controller: "mzInventarioBundle:AdminUsuarios:update" }
    requirements: { _method: post }

usuario_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "mzInventarioBundle:AdminUsuarios:delete" }
    requirements: { _method: post }
