imagen:
    pattern:  /
    defaults: { _controller: "mzInventarioBundle:Imagen:index" }

imagen_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "mzInventarioBundle:Imagen:delete" }
    requirements: { _method: post }
