item_get_delete_form:
    pattern:  /{id}/get_delete_form
    defaults: { _controller: "mzInventarioBundle:Item:getDeleteForm" }
    requirements: { _method: get }
item_show:
    pattern:  /{id}/show
    defaults: { _controller: "mzInventarioBundle:Item:show" }

item_new:
    pattern:  /new
    defaults: { _controller: "mzInventarioBundle:Item:new" }

item_create:
    pattern:  /create
    defaults: { _controller: "mzInventarioBundle:Item:create" }
    requirements: { _method: post }

item_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "mzInventarioBundle:Item:edit" }

item_update:
    pattern:  /{id}/update
    defaults: { _controller: "mzInventarioBundle:Item:update" }
    requirements: { _method: post }

item_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "mzInventarioBundle:Item:delete" }
    requirements: { _method: post }
