profile:
    pattern:  /{id}/profile
    defaults: { _controller: "mzInventarioBundle:Usuario:profile" }

profile_edit:
    pattern:   /{id}/edit
    defaults: { _controller: "mzInventarioBundle:Usuario:edit" }

profile_update:
    pattern:  /{id}/update
    defaults: { _controller: "mzInventarioBundle:Usuario:update" }
    requirements: { _method: post }

change_pass:
    pattern:   /{id}/change_pass
    defaults: { _controller: "mzInventarioBundle:Usuario:changePassword" }

update_pass:
    pattern:  /{id}/update_pass
    defaults: { _controller: "mzInventarioBundle:Usuario:updatePassword" }
    requirements: { _method: post }
