<?php

namespace G4\InventarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UbicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UbicacionRepository extends EntityRepository
{
}
