G4InventarioBundle_categoria:
        resource: "@G4InventarioBundle/Resources/config/routing/categoria.yml"
        prefix:   /categoria

G4InventarioBundle_condicion:
        resource: "@G4InventarioBundle/Resources/config/routing/condicion.yml"
        prefix:   /condicion

G4InventarioBundle_estado:
        resource: "@G4InventarioBundle/Resources/config/routing/estado.yml"
        prefix:   /estado

G4InventarioBundle_ubicacion:
        resource: "@G4InventarioBundle/Resources/config/routing/ubicacion.yml"
        prefix:   /ubicacion

G4InventarioBundle_usuario:
        resource: "@G4InventarioBundle/Resources/config/routing/usuario.yml"
        prefix:   /usuario

G4InventarioBundle_item:
        resource: "@G4InventarioBundle/Resources/config/routing/item.yml"
        prefix:   /item

G4InventarioBundle_prestamo:
        resource: "@G4InventarioBundle/Resources/config/routing/prestamo.yml"
        prefix:   /prestamo

G4InventarioBundle_imagen:
        resource: "@G4InventarioBundle/Resources/config/routing/imagen.yml"
        prefix:   /imagen

homepage:
    pattern:  /
    defaults: { _controller: G4InventarioBundle:Default:index }
