G4\InventarioBundle\Entity\Categoria:
    properties:
        nombre:
            - NotBlank: ~

G4\InventarioBundle\Entity\Condicion:
    properties:
        nombre:
            - NotBlank: ~

G4\InventarioBundle\Entity\Estado:
    properties:
        nombre:
            - NotBlank: ~

G4\InventarioBundle\Entity\Imagen:

G4\InventarioBundle\Entity\Item:
    properties:
        nombre:
            - NotBlank: ~

G4\InventarioBundle\Entity\Prestamo:

G4\InventarioBundle\Entity\Ubicacion:
    properties:
        nombre:
            - NotBlank: ~

G4\InventarioBundle\Entity\Usuario:
    properties:
        nombre:
            - NotBlank: ~

#G4\InventarioBundle\Entity\:
