login:
    pattern:  /login
    defaults: { _controller: "mzInventarioBundle:UsuariosAdmin:login" }

login_check:
    pattern:  /login_check
    defaults: { _controller: "mzInventarioBundle:UsuariosAdmin:login" }

logout:
    pattern:  /logout
    defaults: { _controller: "mzInventarioBundle:UsuariosAdmin:login" }

mzInventarioBundle_categoria:
        resource: "@mzInventarioBundle/Resources/config/routing/categoria.yml"
        prefix:   /categorias

mzInventarioBundle_condicion:
        resource: "@mzInventarioBundle/Resources/config/routing/condicion.yml"
        prefix:   /condiciones

mzInventarioBundle_estado:
        resource: "@mzInventarioBundle/Resources/config/routing/estado.yml"
        prefix:   /estados

mzInventarioBundle_ubicacion:
        resource: "@mzInventarioBundle/Resources/config/routing/ubicacion.yml"
        prefix:   /ubicaciones

mzInventarioBundle_usuario:
        resource: "@mzInventarioBundle/Resources/config/routing/usuario.yml"
        prefix:   /usuario

mzInventarioBundle_admin_usuarios:
        resource: "@mzInventarioBundle/Resources/config/routing/usuarios_admin.yml"
        prefix:   /usuarios

mzInventarioBundle_item:
        resource: "@mzInventarioBundle/Resources/config/routing/item.yml"
        prefix:   /items

mzInventarioBundle_prestamo:
        resource: "@mzInventarioBundle/Resources/config/routing/prestamo.yml"
        prefix:   /prestamos

mzInventarioBundle_imagen:
        resource: "@mzInventarioBundle/Resources/config/routing/imagen.yml"
        prefix:   /imagenes

homepage:
    pattern:  /
    defaults: { _controller: mzInventarioBundle:Item:index }
