parameters:
#    mz_inventory.example.class: mz\InventarioBundle\Example

services:
#    mz_inventory.example:
#        class: %mz_inventory.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
